### ISSUE TITLE
Add documentation for Twig/template usage

### ISSUE THREAD

**Issue by jmcgaha** [TopShelfCraft/Conditions#3]
Thanks for this plugin, it fills a need of what I'd hoped was coming after Conditions were added in Craft 4.
I've played around with this in the control panel and that part is perfect.

I understand you're still in beta but on the front-end I can't quite figure out how I'd use this in an entry query to output results. Do you have any examples yet of the twig side or is that part not ready yet?

Attached is a screenshot of the test I was running, Keywords is a category field.
<img width="466" alt="conditions" src="https://github.com/TopShelfCraft/Conditions/assets/49672/5fc7dd7b-36bd-4293-a7c0-d110bc123279">

Thanks for your help!

**Comment by michaelrog** [comment]
Yup, on my to-do list!

(The field returns the Condition object, which has a `modifyQuery()` method for preparing an ElementQuery to filter elements based on the condition rules.)

**Comment by jmcgaha** [comment]
Thanks for pointing out the modifyQuery() part, that helped me get it working. My example is below

```
{# Get a value from the new condition field #}
{% set condition = craft.entries.section('section-name').slug('entry-with-value-for-condition').one().conditionQueryFieldName %}

{# Make a new query that the condition will alter #}
{% set query = craft.entries.section('section-to-query-on') %}

{# Alter that query #}
{% do condition.modifyQuery(query) %}

{% for entry in query %}
    <li>{{ entry.title }}</li>
{% endfor %}
```

**Comment by michaelrog** [comment]
Yup, that's the way to do it for now.

I'm thinking about adding some shortcut syntax, though... Care to opine?

 👉🏼 #4
